# Generated by Django 5.2.16 on 2026-09-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Alteração"),
                            ("DELETE", "Exclusão"),
                            ("SPECIAL", "Ação especial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UI", "Interface"),
                            ("WEBHOOK", "Webhook"),
                            ("SYSTEM", "Sistema"),
                            ("COMMAND", "Comando"),
                        ],
                        default="UI",
                        max_length=10,
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "object_id"], name="common_audi_entity__f0715f_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="common_audi_actor_i_a7ab54_idx"
                    ),
                ],
            },
        ),
    ]
