# Generated by Django 5.2.8 on 2025-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_member_diet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "remuneration_cents",
                    models.PositiveIntegerField(
                        default=0, help_text="Valor em centavos. Pode ser zero."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(blank=True, related_name="duties", to="users.member"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
