# Generated by Django 5.2.8 on 2025-11-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("duties", "0001_initial"),
        ("users", "0002_alter_member_diet"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADO", "Planejado"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PLANEJADO",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_entries",
                        to="duties.duty",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="agenda_entries", to="users.member"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "duty__name"],
            },
        ),
    ]
