# Generated by Django 5.2.8 on 2026-03-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaentry",
            name="notes",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
    ]
