# Generated by Django 5.2.16 on 2026-10-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_agendaentry_created_by_agendaentry_updated_by"),
        ("duties", "0002_duty_created_by_duty_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaentry",
            name="duty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agenda_entries",
                to="duties.duty",
            ),
        ),
    ]
