# Generated by Django 5.2.8 on 2025-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField(blank=True)),
                (
                    "heard_about",
                    models.TextField(
                        blank=True,
                        help_text="How the member heard about the community lunch.",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUSTENTADOR", "Sustentador"),
                            ("MENSALISTA", "Mensalista"),
                            ("AVULSO", "Avulso"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("VEGANO", "Vegano"),
                            ("VEGETARIANO", "Vegetariano"),
                            ("CARNIVORO", "Carnivoro"),
                        ],
                        default="CARNIVORO",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
