# Generated by Django 5.2.8 on 2025-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="diet",
            field=models.CharField(
                choices=[
                    ("VEGANO", "Vegano"),
                    ("VEGETARIANO", "Vegetariano"),
                    ("CARNIVORO", "Carnivoro"),
                ],
                max_length=20,
            ),
        ),
    ]
