# Generated by Django 5.2.8 on 2025-12-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_member_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_child",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="users.member",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUSTENTADOR", "Sustentador"),
                    ("MENSALISTA", "Mensalista"),
                    ("AVULSO", "Avulso"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
