# Generated by Django 5.2.8 on 2025-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_member_is_child_member_responsible_alter_member_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
