# Generated by Django 5.2.8 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_member_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "heard_about",
                    models.TextField(
                        blank=True,
                        help_text="How the member heard about the community lunch.",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUSTENTADOR", "Sustentador"),
                            ("MENSALISTA", "Mensalista"),
                            ("AVULSO", "Avulso"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("VEGANO", "Vegano"),
                            ("VEGETARIANO", "Vegetariano"),
                            ("CARNIVORO", "Carnivoro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("REJEITADO", "Rejeitado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicRegistrationChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("VEGANO", "Vegano"),
                            ("VEGETARIANO", "Vegetariano"),
                            ("CARNIVORO", "Carnivoro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="children",
                        to="users.publicregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
