# Generated by Django 5.2.8 on 2026-03-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_publicregistration_publicregistrationchild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="address",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="heard_about",
            field=models.TextField(
                blank=True,
                help_text="How the member heard about the community lunch.",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="observations",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="publicregistration",
            name="address",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="publicregistration",
            name="heard_about",
            field=models.TextField(
                blank=True,
                help_text="How the member heard about the community lunch.",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="publicregistration",
            name="observations",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="publicregistration",
            name="review_notes",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="publicregistrationchild",
            name="observations",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
    ]
