# Generated by Django 5.2.8 on 2025-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALMOCO", "Pagamento de almoço"),
                            ("DOACAO", "Doação"),
                            ("NOTA", "Compra / Nota fiscal"),
                            ("STAFF", "Pagamento de equipe"),
                            ("DESPESA", "Despesa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("value_cents", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
