# Generated by Django 5.2.8 on 2025-11-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
        ("lunch", "0002_lunch_remaining_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialentry",
            name="lunch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_entry",
                to="lunch.lunch",
            ),
        ),
    ]
