# Generated by Django 5.2.8 on 2025-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_financialentry_lunch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("ALMOCO", "Pagamento de almoço"),
                    ("DOACAO", "Doação"),
                    ("NOTA", "Compra / Nota fiscal"),
                    ("STAFF", "Pagamento de equipe"),
                    ("DESPESA", "Despesa"),
                    ("ESTORNO", "Estorno"),
                ],
                max_length=20,
            ),
        ),
    ]
