# Generated by Django 5.2.8 on 2026-01-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_alter_financialentry_category"),
        ("lunch", "0004_remove_lunch_lunch_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialentry",
            name="package",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_entry",
                to="lunch.package",
            ),
        ),
    ]
