# Generated by Django 5.2.8 on 2026-03-25 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0004_financialentry_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentry",
            name="description",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
