# Generated by Django 5.2.8

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lunch", "0011_format_generated_description_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("document_type", models.CharField(choices=[("NFE", "NF-e"), ("NFCE", "NFC-e")], max_length=4)),
                ("environment", models.CharField(choices=[("HOMOLOGATION", "Homologação"), ("PRODUCTION", "Produção")], max_length=20)),
                ("status", models.CharField(choices=[("PENDING", "Pendente"), ("PROCESSING", "Processando"), ("AUTHORIZED", "Autorizada"), ("REJECTED", "Rejeitada"), ("CANCELLED", "Cancelada")], default="PENDING", max_length=20)),
                ("sale_date", models.DateField()),
                ("recipient", models.JSONField(default=dict)),
                ("items", models.JSONField(default=list)),
                ("payment_methods", models.JSONField(default=list)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("focus_status", models.CharField(blank=True, max_length=80)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("series", models.CharField(blank=True, max_length=20)),
                ("access_key", models.CharField(blank=True, max_length=44)),
                ("protocol", models.CharField(blank=True, max_length=30)),
                ("xml_url", models.URLField(blank=True, max_length=500)),
                ("danfe_url", models.URLField(blank=True, max_length=500)),
                ("sefaz_code", models.CharField(blank=True, max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_fiscal_documents", to=settings.AUTH_USER_MODEL)),
                ("lunch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_documents", to="lunch.lunch")),
                ("package", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fiscal_documents", to="lunch.package")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(("lunch__isnull", False), ("package__isnull", True)))
                    | (models.Q(("lunch__isnull", True), ("package__isnull", False)))
                ),
                name="fiscal_document_has_exactly_one_source",
            ),
        ),
    ]
