# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("fiscal", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="FiscalWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                ("provider_event", models.CharField(blank=True, max_length=80)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSED", "Processado"),
                            ("IGNORED", "Ignorado"),
                            ("FAILED", "Falhou"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="fiscal.fiscaldocument",
                    ),
                ),
            ],
            options={"ordering": ["-received_at", "-id"]},
        )
    ]
