# Generated by Django 5.2.16 on 2026-09-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operator_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("access_dashboard", "Pode acessar o dashboard"),
                    ("manage_lunch", "Pode gerenciar almoços e pacotes"),
                    ("manage_financial", "Pode gerenciar o financeiro"),
                    ("manage_fiscal", "Pode gerenciar notas fiscais"),
                    ("manage_credits", "Pode gerenciar trocas e créditos"),
                    ("manage_agenda", "Pode gerenciar a agenda"),
                    ("manage_members", "Pode gerenciar integrantes e cadastros"),
                    ("manage_duties", "Pode gerenciar funções"),
                ],
            },
        ),
    ]
