# Generated by Django 5.2.16 on 2026-09-30 20:30

from django.db import migrations


def split_legacy_lunch_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("auth", "User")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="authentication",
        model="operatorprofile",
    )
    lunches_permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="manage_lunches",
        defaults={"name": "Pode gerenciar almoços"},
    )
    packages_permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="manage_packages",
        defaults={"name": "Pode gerenciar pacotes"},
    )
    legacy_permission = Permission.objects.filter(
        content_type=content_type,
        codename="manage_lunch",
    ).first()
    if not legacy_permission:
        return

    for user in User.objects.filter(user_permissions=legacy_permission).distinct():
        user.user_permissions.add(lunches_permission, packages_permission)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatorprofile",
            options={
                "permissions": [
                    ("manage_lunches", "Pode gerenciar almoços"),
                    ("manage_packages", "Pode gerenciar pacotes"),
                    ("manage_financial", "Pode gerenciar o financeiro"),
                    ("manage_fiscal", "Pode gerenciar notas fiscais"),
                    ("manage_credits", "Pode gerenciar trocas e créditos"),
                    ("manage_agenda", "Pode gerenciar a agenda"),
                    ("manage_members", "Pode gerenciar integrantes e cadastros"),
                    ("manage_duties", "Pode gerenciar funções"),
                ]
            },
        ),
        migrations.RunPython(split_legacy_lunch_permission, migrations.RunPython.noop),
    ]
