# Generated by Django 5.2.8 on 2025-11-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_member_diet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_cents", models.PositiveIntegerField(help_text="Valor em centavos.")),
                ("date", models.DateField()),
                (
                    "lunch_type",
                    models.CharField(
                        choices=[("AVULSO", "Avulso"), ("PACOTE", "Pacote")], max_length=10
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PAGO", "Pago"), ("EM_ABERTO", "Em aberto")], max_length=10
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("package_expiration", models.DateField(blank=True, null=True)),
                (
                    "package_status",
                    models.CharField(
                        blank=True,
                        choices=[("EXPIRADO", "Expirado"), ("VALIDO", "Válido")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lunches",
                        to="users.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
