# Generated by Django 5.2.8 on 2026-01-17 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0003_lunch_payment_mode"),
        ("users", "0005_alter_member_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lunch",
            name="lunch_type",
        ),
        migrations.RemoveField(
            model_name="lunch",
            name="package_expiration",
        ),
        migrations.RemoveField(
            model_name="lunch",
            name="package_status",
        ),
        migrations.RemoveField(
            model_name="lunch",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="lunch",
            name="remaining_quantity",
        ),
        migrations.AlterField(
            model_name="lunch",
            name="payment_mode",
            field=models.CharField(
                choices=[("PIX", "Pix"), ("CARTAO", "Cartão"), ("DINHEIRO", "Dinheiro")],
                default="PIX",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_cents", models.PositiveIntegerField(help_text="Valor em centavos.")),
                ("date", models.DateField(help_text="Data de compra do pacote.")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PAGO", "Pago"), ("EM_ABERTO", "Em aberto")], max_length=10
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("PIX", "Pix"), ("CARTAO", "Cartão"), ("DINHEIRO", "Dinheiro")],
                        default="PIX",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("remaining_quantity", models.PositiveIntegerField()),
                ("expiration", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("EXPIRADO", "Expirado"), ("VALIDO", "Válido")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="users.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lunch",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunches",
                to="lunch.package",
            ),
        ),
    ]
