# Generated by Django 5.2.8 on 2026-01-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0004_remove_lunch_lunch_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="unit_value_cents",
            field=models.PositiveIntegerField(default=0, help_text="Valor unitário em centavos."),
            preserve_default=False,
        ),
    ]
