# Generated by Django 5.2.8 on 2026-03-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0006_alter_lunch_payment_mode_alter_package_payment_mode"),
        ("users", "0007_alter_member_address_alter_member_heard_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunch",
            name="credit_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_paid_lunches",
                to="users.member",
            ),
        ),
    ]
