# Generated by Django 5.2.16 on 2026-10-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lunch", "0012_lunch_created_by_lunch_updated_by_package_created_by_and_more"),
        ("users", "0008_member_created_by_member_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lunches",
                to="users.member",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="users.member",
            ),
        ),
    ]
