# Generated by Django 5.2.8 on 2026-03-27 12:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0002_alter_agendaentry_notes"),
        ("lunch", "0006_alter_lunch_payment_mode_alter_package_payment_mode"),
        ("users", "0007_alter_member_address_alter_member_heard_about_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("CREDITO", "Crédito"), ("DEBITO", "Débito")], max_length=10
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("AGENDA", "Agenda"),
                            ("MANUAL", "Manual"),
                            ("LUNCH", "Almoço"),
                            ("ESTORNO", "Estorno"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value_cents", models.PositiveIntegerField()),
                (
                    "description",
                    models.TextField(
                        blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_entries",
                        to="agenda.agendaentry",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_beneficiary_entries",
                        to="users.member",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lunch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_entry",
                        to="lunch.lunch",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_entries",
                        to="users.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("value_cents__gt", 0)),
                        name="credits_entry_value_cents_gt_zero",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("agenda_entry__isnull", False),
                            ("entry_type", "CREDITO"),
                            ("origin", "AGENDA"),
                        ),
                        fields=("agenda_entry", "owner", "origin", "entry_type"),
                        name="credits_unique_agenda_credit_per_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("entry_type", "DEBITO"), ("lunch__isnull", False), ("origin", "LUNCH")
                        ),
                        fields=("lunch", "origin", "entry_type"),
                        name="credits_unique_lunch_debit",
                    ),
                ],
            },
        ),
    ]
