# Generated by Django 5.2.16 on 2026-10-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_alter_agendaentry_duty"),
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditentry",
            name="agenda_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_entries",
                to="agenda.agendaentry",
            ),
        ),
    ]
